#!/usr/bin/env bash
# Install haproxy and config 2 server
apt-get update
apt-get upgrade -y
apt install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.4 -y
apt-get -y install haproxy=2.4.\*
echo "ENABLED=1" >> /etc/default/haproxy
sed -i '/504.http/a \\nlisten http-in\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 56304-web-01 18.210.16.34:80 check\n\tserver 56304-web-02 35.153.83.89:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy start
